### ISSUE TITLE
verifyIdToken invalid id token public key id ignoreExpiration

### ISSUE THREAD

**Issue by hoerlanton** [A-Tokyo/apple-signin-auth#115]
Hi!

I am having an issue with your library and I am not sure how to solve or what I am doing wrong. Therefore I thought I open an issue here. I hope this approach is ok with you.

I implemented my react native and node js authentication based on this tutorial: 
https://rossbulat.medium.com/react-native-sign-in-with-apple-75733d3fbc3
 
I use your library in the backend, and I try to verify the IdToken with the ignoreExpiration flag set to true.

`result = await appleSignin.verifyIdToken(token, {
  audience: config.CLIENT_ID_APPLE,
  ignoreExpiration: true, // ignore token expiry (never expires)
});`

But I get the following error:

> JsonWebTokenError: error in secret or public key callback: input error: Invalid id token public key id at /app/node_modules/jsonwebtoken/verify.js:96:19 at _getIdTokenApplePublicKey (/app/node_modules/apple-signin-auth/lib/index.js:1:5730) at runMicrotasks () at processTicksAndRejections (internal/process/task_queues.js:95:5)

I also posted this question on SO: https://stackoverflow.com/questions/71570842/apple-auth-node-js-react-native-ignore-expiration-of-id-token-in-back-end

I am not sure what I am doing wrong here and any help is highly appreciated. @A-Tokyo maybe you have a hint for me?

Thanks for the efforts!

**Comment by hoerlanton** [comment]
What I found out is that the public keys from the apple endpoint: https://appleid.apple.com/auth/keys Are changing over time. Therefore the key ids are not matching with the key id from the identity token I saved in the Async Storage. It cannot find the matching kid in the public keys because they are not there anymore. I am thinking about what solution to implement.

**Comment by A-Tokyo** [comment]
@hoerlanton Thanks for the detailed description! 

Apple's public keys change over time, which is why we have implemented a [cache](https://github.com/A-Tokyo/apple-signin-auth/blob/main/src/index.js#L99) that holds Apple's valid public keys, and refetches the new keys ones the old ones are invalid.

I think you shouldn't store apple's ID token in your async storage. It should be used once. It should be sent to your backend and your backend should then respond with a longer lived authentication token. 

Rely on Apple auth only for the first handshake, then rely on your own implementation.

**Comment by hoerlanton** [comment]
@A-Tokyo thanks for your comment and the great suggestion, how to improve my authentication. I just implemented those changes. By the way: I like your great library!

**Comment by A-Tokyo** [comment]
@hoerlanton My pleasure! Thanks for your compliment ( :

Let me know if you need any further help!

**Comment by niraj-khatiwada** [comment]
Hey, I'm having a hard time figuring out why the id_token provided from Firebase Apple Login in Android seems to be invalid every time. The `appleSignin.verifyIdToken` works fine with id_tokens that we use for apple login in ios devices and apple login on the web. But we are using Firebase's apple authentication method to login into android. It returns the id_token the same way as other platforms(web, ios, etc), but the id token is always invalid. It always says:
```
-- JsonWebTokenError: error in secret or public key callback: input error: Invalid id token public key id
```  

I even tried setting `aud` to the one with firebase and used the private key that we need to add in Firebase but nothing seems to work. I think there is a way different way to validate the id_token that we get from the firebase apple login. So if someone could shed some light on it, that would be a great help.

Thanks for making a great library. Cheers!
