### ISSUE TITLE
Is this OAuth2 client?

### ISSUE THREAD

**Issue by wirekang** [A-Tokyo/apple-signin-auth#125]
Sign in with Apple is not following OAuth2 protocol? Can I just use OAuth2 package for Apple? I am so confusing why should I use this package.

**Comment by A-Tokyo** [comment]
This package is a wrapper that makes it easy to use apple authentication with a nodejs backend. You can implement all of these steps/functions manually in your backend, or you can just use this library.

Here's a nice article on how to implement apple auth full stack: https://dev.to/onygami/how-to-add-signin-with-apple-on-your-website-43m9

**Comment by A-Tokyo** [comment]
Hey there! ( : 

This package is a wrapper that makes it easy to use apple authentication with a nodejs backend. You can implement all of these steps/functions manually in your backend, or you can just use this library.

Here's a nice article on how to implement apple auth full stack: https://dev.to/onygami/how-to-add-signin-with-apple-on-your-website-43m9
