### ISSUE TITLE
revokeAuthorizationToken returns nothing

### ISSUE THREAD

**Issue by sidan5** [A-Tokyo/apple-signin-auth#132]
I'm using 

    const clientSecret = appleSignin.getClientSecret({
    clientID: "com.company.app", // Apple Client ID
    teamID: "teamID", // Apple Developer Team ID.
    privateKey: "PRIVATE_KEY_STRING", // private key associated with your client ID. -- Or provide a "privateKeyPath" property instead.
    keyIdentifier: "XXXXXXXXXX", // identifier of the private key. - can be found here https://developer.apple.com/account/resources/authkeys/list
    // OPTIONAL
    expAfter: 15777000, // Duration after which to expire JWT
    });

    const options = {
    clientID: "com.company.app", // Apple Client ID
    clientSecret
    };

    try {
      const response = appleSignin.revokeAuthorizationToken(refreshToken, options);
    } catch (err) {
      console.error(err);
    }

'response' I'm getting is always empty. I'm setting up 'refreshToken' as some dummy string and still no error. Please help.

Everything is set up correctly and I'm retrieving clientSecret correctly.

**Comment by sidan5** [comment]
@zicyApp Can you look into this?

**Comment by zicyApp** [comment]
@sidan5 I think it should be `await` appleSignin.revokeAuthorizationToken(refreshToken, options);

**Comment by sidan5** [comment]
> @sidan5 I think it should be `await` appleSignin.revokeAuthorizationToken(refreshToken, options);

It's not recognizing as asynchronous function...

**Comment by zicyApp** [comment]
@sidan5 also the revoke should only return an empty 200 on success

**Comment by sidan5** [comment]
@A-Tokyo Still get no error and an empty response for any dummy token. Expect to get some error response.

**Comment by zicyApp** [comment]
@sidan5 @A-Tokyo I've done some extra tests with the revoke call.

We can only get `{ error: 'invalid_client' }` when the client_id or the client_secret is invalid. With a dummy/expired token you can only get an empty response.

I also had a typo in the last parameter `token_type_hint`, but it's optional so the call should work without that anyway.

**Comment by sidan5** [comment]
@zicyApp so how do you know when success? 🤔

**Comment by zicyApp** [comment]
@sidan5 I test it normally with the complete login flow

- Login with apple in your app
- Save access/refresh token
- Login to https://appleid.apple.com/ to make sure you the authorized app is on the list
- Call revoke with the valid credentials 
- On https://appleid.apple.com/ the previously authorized app should not be there anymore

**Comment by A-Tokyo** [comment]
@sidan5 I think @zicyApp's answer solved this issue. Please reopen the issue if you're still facing this problem.

@zicyApp Thanks for your contributions!
