### ISSUE TITLE
 o.URL is not a constructor

### ISSUE THREAD

**Issue by adasarpan404** [A-Tokyo/apple-signin-auth#143]
While using verifyIdToken

**Comment by A-Tokyo** [comment]
Which nodeJS version? @adasarpan404

**Comment by adasarpan404** [comment]
Nodejs v12.22.10

**Comment by A-Tokyo** [comment]
Unfortunately this is an issue with NodeJS v12, this library supports >= v14

Can you upgrade your nodeJS version?

If not, you can work around this by adding a polyfill for URL constructor

**Comment by adasarpan404** [comment]
I have been working on my Organisation's project. 
They are using some library which does not get installed in v12.

@A-Tokyo Thanks I will try your suggestion

**Comment by A-Tokyo** [comment]
@adasarpan404 Welcome, please reopen the issue if there's anyth I can help with
