### ISSUE TITLE
jsonwebtoken dependency version has security vulnerabilities

### ISSUE THREAD

**Issue by liegeandlief** [a-tokyo/apple-signin-auth#153]
The version of `jsonwebtoken` used (8.5.1) contains various security vulnerabilities including this high severity issue: https://github.com/advisories/GHSA-27h2-hvpr-p74q

This dependency should be bumped to version 9.0.0 where these vulnerabilities have been addressed.

**Comment by liegeandlief** [comment]
https://github.com/a-tokyo/apple-signin-auth/pull/154

**Comment by a-tokyo** [comment]
done!

**Comment by liegeandlief** [comment]
Thank you!

**Comment by liegeandlief** [comment]
@a-tokyo will the updated package version be published to NPM automatically or does it require manually doing?

**Comment by a-tokyo** [comment]
@liegeandlief Welcome!

It's automatic, however the tests failed. I fixed the tests (3rd party api change) and it should release in a couple of mins

**Comment by liegeandlief** [comment]
Sorry to chase, but the new release still hasn't happened. Will it happen soon? Thanks and happy new year!

**Comment by a-tokyo** [comment]
@liegeandlief Hey! Thanks for your patience ( : -- It's done now, Happy new year!

https://github.com/a-tokyo/apple-signin-auth/releases/tag/1.7.5
