### ISSUE TITLE
Error when fetching apple keys with jwt.verify causes unhandled promise rejection

### ISSUE THREAD

**Issue by DjangoCrema** [a-tokyo/apple-signin-auth#182]
From time to time, we face an unhandled promise rejection inside our system. Would be great to fix it, we can't catch the error on our end.

{"level":"error","message":"Unhandled: TypeError: Cannot read properties of undefined (reading 'map') Cannot read properties of undefined (reading 'map')","stack":"TypeError: Cannot read properties of undefined (reading 'map')\n    at _getApplePublicKeys (/app/node_modules/apple-signin-auth/lib/index.js:1:5928)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async _getIdTokenApplePublicKey (/app/node_modules/apple-signin-auth/lib/index.js:1:6399)"

`secretOrPublicKey is a string (utf-8 encoded), buffer, or KeyObject containing either the secret for HMAC algorithms, or the PEM encoded public key for RSA and ECDSA. If jwt.verify is called asynchronous, secretOrPublicKey can be a function that should fetch the secret or public key`

Suggestion:
Make _getIdTokenApplePublicKey more resilient to errors and handle them properly. 
```/** Gets the Apple Public Key corresponding to the JSON's header  */
const _getIdTokenApplePublicKey = async (
  header: string,
  cb: (?Error, ?string) => any,
): Function => {
  // attempt fetching from cache
  if (APPLE_KEYS_CACHE[header.kid]) {
    return cb(null, APPLE_KEYS_CACHE[header.kid]);
  }
  // fetch and cache current Apple public keys
  try {
    await _getApplePublicKeys();
  } catch (error) {
    return cb(new Error('input error: Invalid id token public key id'));  
  }

  // attempt fetching from cache
  if (APPLE_KEYS_CACHE[header.kid]) {
    return cb(null, APPLE_KEYS_CACHE[header.kid]);
  }
  // key was not fetched - highly unlikely, means apple is having issues or somebody faked the JSON
  return cb(new Error('input error: Invalid id token public key id'));
};
```

**Comment by a-tokyo** [comment]
@DjangoCrema Thank you for submitting a recommended solution alongside the issue. I am fixing it now and will be releasing asap.

**Comment by a-tokyo** [comment]
Here's the final fix: 

We will catch the error if it happens but we will not throw it, instead we will try to rely on the cache to fulfill the authentication request and not disturb the users. If relying on the cache still fails, then we will throw the error.

This should handle your issue while also reducing the user facing issues that were caused when this happened.

Thank you for reporting
