### ISSUE TITLE
How to import this library to Ionic?

### ISSUE THREAD

**Issue by Carsak** [A-Tokyo/apple-signin-auth#21]
Hello,
thanks for library

I want to use this library in Ionic3, Angular based framework.

Steps:
1. npm install --save apple-signin-auth
2. import from node modules `import appleSignIn from 'apple-signin-auth/lib';`
3. run code in component
```
const options = {
      clientID: 'myClientId',
      redirectUri: 'http://someUrl',
      state: 'state',
      responseMode: 'form_post',
      scope: 'name email'
    };
     

    let url = appleSignIn(options);
    console.warn(url);
```

and get error 

`ERROR TypeError: __WEBPACK_IMPORTED_MODULE_6_apple_signin_auth_lib___default(...) is not a function`

![image](https://user-images.githubusercontent.com/9497934/89701847-a2778700-d943-11ea-9901-9818493a0037.png)

**Comment by A-Tokyo** [comment]
Hey! @Carsak, I am not sure if the library would work with angular. However I think the import SHOULD work.

- Can you please provide me with a very simple demo that I can debug?
> - Simply start a new angular app (do the equivalent of `create-react-app myapp`) and import the library and paste a link here.

I will debug and fix the issue if any

**Comment by A-Tokyo** [comment]
@Carsak I just noticed that there's a bug in the code snippet provided. The error says `appleSignIn()` is not a function, and it is not a function indeed.

Did you mean to use the code below?
```js
appleSignIn.appleSignin.getClientSecret(options);
```

The available functions are:
```js
{getAuthorizationUrl,getClientSecret,getAuthorizationToken,refreshAuthorizationToken,verifyIdToken,_getApplePublicKeys}
```
