### ISSUE TITLE
Error getAuthorizationToken => invalid_client

### ISSUE THREAD

**Issue by Nikosmonaut** [A-Tokyo/apple-signin-auth#28]
Hello. Could someone explain me how getAuthorizationToken should work please ?
Because I get this error => 'invalid_client'

What I don't understand is why 
```
const COMMON_HEADERS = {
  'Content-Type': 'application/json',
};
```

is used, meanwhile Apple says it should be ([here](https://developer.apple.com/documentation/sign_in_with_apple/generate_and_validate_tokens))

> form-data
> 
> The list of input parameters required for the server to validate the authorization code or refresh token.
> Content-Type: application/x-www-form-urlencoded

So tweaking a little the code like this
```
const { URLSearchParams } = require('url');
 
const params = new URLSearchParams();
params.append('code', authorizationCode);
params.append('grant_type', 'authorization_code');
params.append('client_secret', clientSecret);
params.append('client_id', clientID);
 
fetch('https://appleid.apple.com/auth/token', { method: 'POST', body: params })
    .then(res => res.json())
    .then(json => console.log(json));
```

works fine, but not with application/json. 

Anyone got it work as is ?

**Comment by A-Tokyo** [comment]
Hey @Nikosmonaut! I think a mistake was made were the headers were sent with all requests and not just the key fetching ones. should be fixed in 1.0.10 👍
