### ISSUE TITLE
Proxy issue

### ISSUE THREAD

**Issue by NitinHsharma** [A-Tokyo/apple-signin-auth#31]
Hey Team,

How do we use a proxy for this package, right now it is failing. should I change node-fetch with node-fetch-with-proxy and raise the request?

**Comment by A-Tokyo** [comment]
Hey! I checked this https://stackoverflow.com/questions/60162485/how-to-configure-node-fetch-to-use-the-company-proxy

And thought about the following:
What if we expose a `_setFetchOptions` or `_setFetch` functions that allows users to manipulate the fetch params?

This way you would be able to call:
```js
appleSigninAuth._setFetch(nodeFetchProxy);
```
and it'd set the fetch function

**Comment by NitinHsharma** [comment]
Yeah, that would also work like a champ,
But Generally, we set proxies in env variable and any request module just uses it.

Anyways will work for me, let me know if I can work for it or you will take care of it?

**Comment by A-Tokyo** [comment]
@NitinHsharma Can you please open a PR with the _setFetch function? (We have a similar function called _getApplePublicKeys)

Make sure you update the docs and keep flow types intact ✨

**Comment by A-Tokyo** [comment]
I think this would do:
```js
/**
 * Fetch function
 */
let fetch = rawFetch;

/**
 * Sets the fetch function
 * 
 * Can be used to pass a proxy fetch function or to override headers and params
 */
const _setFetch = (fetchFn: Function) => {
  fetch = fetchFn;
};
```

**Comment by NitinHsharma** [comment]
Raised the request with the above code.
Thank you so much for quick support, Really appreciated

PR: https://github.com/A-Tokyo/apple-signin-auth/pull/32

**Comment by A-Tokyo** [comment]
Awesome job @NitinHsharma , It's ready now 🚀
