### ISSUE TITLE
Optional redirectUri to get getAuthorizationToken

### ISSUE THREAD

**Issue by Ariandr** [A-Tokyo/apple-signin-auth#4]
Hi, the issue was explained in the different repository by which you were inspired. But I'm not sure it's enough to make the lib work in a correct way to correctly verify data from iOS (authorization code)
https://github.com/Techofficer/node-apple-signin/issues/6

**Comment by A-Tokyo** [comment]
Hey @Ariandr The field is optional atm, so the library no longer throws any errors.

For verification: Can you rely on [verifyIdToken](https://github.com/A-Tokyo/apple-signin-auth#3-verify-token-signature-and-get-unique-users-identifier)?

**Comment by Ariandr** [comment]
Hi @A-Tokyo 
Yes, we rely on this right now.
But the better way would be to verify the user by `authorizationCode` because it's valid for 10 minutes. And Apple says in their documentation it's specifically made for this purpose.

https://developer.apple.com/documentation/signinwithapplerestapi/verifying_a_user

<img width="560" alt="Screenshot at Mar 13 11-56-16" src="https://user-images.githubusercontent.com/13591333/76610688-f52e4d80-6521-11ea-9a7b-feac3d90f7fc.png">

It more complex, but it's more secure. The flow described here: https://dev.to/michalrogowski/why-sign-in-with-apple-may-take-you-more-than-5-minutes-and-how-it-works-55p6

**Comment by A-Tokyo** [comment]
I see what you mean, but I can't extract anything I can help with atm. 

How can I help? 💪

**Comment by Ariandr** [comment]
Hi @A-Tokyo
Let's put this on hold for now. When I have free time, I will create a new issue with the description of implementing this better way.
Thanks for your desire to help 🙂

**Comment by Ariandr** [comment]
I will close it for now

**Comment by A-Tokyo** [comment]
@Ariandr Awesome (: Let me know whenever I can help 💪
