### ISSUE TITLE
require('apple-signin-auth') statement is not working and getting error is not a function

### ISSUE THREAD

**Issue by dharm-4** [A-Tokyo/apple-signin-auth#6]
Below code sample is not working with the latest version of code it is not supporting require statement.

`const appleSignin = require('apple-signin-auth');`
`const options = {..}`
`const authorizationUrl =  appleSignin.getAuthorizationUrl(options);`
`console.log(authorizationUrl);`

Error::
const authorizationUrl =  appleSignin.getAuthorizationUrl(options);
                                      ^
TypeError: appleSignin.getAuthorizationUrl is not a function

can anyone please help me to get this shorted.

Looking forward to the solution.

Thanks,

**Comment by A-Tokyo** [comment]
@dharm-4 Okay, I'll fix this today 👍 , as a workaround you can use appleSignin.default. getAuthorizationUrl

**Comment by A-Tokyo** [comment]
Thanks for pointing it out!

Fixed in https://github.com/A-Tokyo/apple-signin-auth/releases/tag/1.0.6, you can try it here https://npm.runkit.com/apple-signin-auth

Problem: It was a babel transform issue : ), I simply ensured that the functions are exported as well to work flawlessly with commonJS

**Comment by dharm-4** [comment]
Thanks, @A-Tokyo  for the quick response and quick fix!

Really appreciable.

**Comment by A-Tokyo** [comment]
@dharm-4 My pleasure ( :
