### ISSUE TITLE
Next.js error: Global CSS cannot be imported from within node_modules.

### ISSUE THREAD

**Issue by denny7** [A-Tokyo/apple-signin-auth#65]
Cannot build using next.js because of CSS importing.

**Comment by A-Tokyo** [comment]
@denny7 What CSS? Did you maybe confuse this library with https://github.com/A-Tokyo/react-apple-signin-auth?

**Comment by A-Tokyo** [comment]
Please reopen if the issue is indeed in this library OR reopen in https://github.com/A-Tokyo/react-apple-signin-auth if it's related to that.

Thanks for your time!
