### ISSUE TITLE
accessToken is not valid.

### ISSUE THREAD

**Issue by taylor928908** [A-Tokyo/apple-signin-auth#92]
Hi. The solution you created has helped me a lot.

await appleSignin provided by NPM apple-signin-auth
       Succeeded in getting tokenResponse via .getAuthorizationToken() .

But the length of accessToken is too short.

The values I actually received are:
```
{
   "access_token": "ac6b736c7f2624fa1b9bea9987365d736.0.sysy.8f0JHW_a7jOrlPzCTYxIwQ",
   "token_type": "Bearer",
   "expires_in": 3600,
   "refresh_token": "rfe4bae11488c423d8010b12a7d581d5d.0.sysy.K1YJnRWIo64ghcuAjrZLow",
   "id_token": "ABCD...."
}
```
I checked https://jwt.io/ to validate the access_token, but the token is not valid.

can you give me some advice?

**Comment by A-Tokyo** [comment]
Your tokens have `sysy` instead of the actual value which is weird, I can only think of the input values being incorrect or having typos

**Comment by A-Tokyo** [comment]
will close this for now! ( : Let me know if I can still help
